# Parser config
parsed_dir: data/processed/scand # where to store/read parsed bags
sample_rate: 4.0 # number of frames per second (hz)
pred_len: 20 # action prediction length
obs_len: 6 # observation length
num_ped: 6 # max number of pedestrian
linear_threshold: 0.03 # Minimum error to be considered for non linear traj
musohu:
  bags_dir: /media/songd/Crucial X9/data/social_nav/musohu
  ang_offset: 0.0
  skip_first_seconds: 8 # skip the first few seconds
  skip_traj_shorter: 50 # skip trajectories with fewer frames than skip_traj_short_traj
  topics: # topic names for each sensor
    depth: ["/zed2/zed_node/depth/depth_registered/compressed"]
    rgb: ["/zed2/zed_node/rgb/image_rect_color/compressed"]
    odom: ["/zed2/zed_node/odom"]
    cmd_vel: ["/action"] # linear and angular velocities
    lidar: ["/velodyne_points"]
  functions:
    rgb: "process_rgb"
    depth: "process_rgb"
    lidar: "process_pointclouds"
    odom: "nav_to_xy_yaw"

scand:
  bags_dir: /media/songd/Crucial X9/data/social_nav/scand
  ang_offset: 0.0
  skip_first_seconds: 5 # skip the first few seconds
  skip_traj_shorter: 50 # skip trajectories with fewer frames than skip_traj_short_traj
  jackal: # topic names for each sensor
    # rgb: ["/left/image_color/compressed"]
    rgb: ["/camera/rgb/image_raw/compressed"]
    odom: ["/jackal_velocity_controller/odom"]
    cmd_vel: ["/bluetooth_teleop/joy"] # joystick
    lidar: ["/velodyne_points"]
  spot: # topic names for each sensor
    # rgb: ["/spot/camera/frontleft/image/compressed"]
    rgb: ["/image_raw/compressed", "/spot/camera/frontleft/image/compressed"]
    odom: ["/odom"]
    cmd_vel: ["/joystick"] # linear and angular velocities
    lidar: ["/velodyne_points"]
  functions:
    rgb: "process_rgb"
    lidar: "process_pointclouds"
    odom: "nav_to_xy_yaw_scand"

sbpd:
  bags_dir: /media/songd/Crucial X9/data/social_nav/sbpd
  ang_offset: 0.0
  skip_first_seconds: 0 # skip the first few seconds
  skip_traj_shorter: 1000 # skip trajectories with fewer frames than skip_traj_short_traj
  topics: # topic names for each sensor
    rgb: ["/zed2/zed_node/rgb/image_rect_color/compressed"]
    odom: ["/odom"]
    cmd_vel: ["/cmd_vel"] # linear and angular velocities
    lidar: ["/velodyne_points"]
  functions:
    rgb: "process_rgb"
    lidar: "process_pointclouds"
    odom: "nav_to_xy_yaw"

