dataset:
  index_file: "data/processed/samples/samples_train_index.json"
  only_human_visable: true
  only_nonlinear: true
  resize: [224, 224] #[192, 192]
  metric_waypoint_spacing: 1.0

train_params:
  seed: 42
  batch_size: 16
  epochs: 50           # total downstream epochs (Stage-1 + Stage-2)
  stage1_epochs: 5     # Stage-1: freeze backbone, train head only
  head_lr: 5e-4        # LR for the MLP head (both stages)
  backbone_lr: 1e-4    # LR for backbone during Stage-2
  weight_decay: 1e-5
  num_workers: 4
  save_every: 2
  amp: false
  clip_grad_norm: 1.0
  sample_ratio: 1.0     # set <1.0 to subsample the dataset for quick runs
  sample_seed: 42
  log_every: 50

model:
  # Must match the d used in your pretext checkpoint
  d: 256
  d_goal: 64
  head_hidden_mult: 2
  num_layers: 3

  input:
    T_obs: 6
    T_pred: 6
    N_human: 3
    N_joints: 17

  image_encoder:
    name: dino #resnet18
    pretrained: true
    freeze_bn: true
    freeze_stem: false
    channels_last: true

directory:
  model_dir: /home/songd/research/pose2nav/checkpoint/downstream/   
  pretext_ckpt: /home/songd/research/pose2nav/checkpoint/pretext/socialnav_pretext_vicreg_d256_20250829_061157_best-best.pth

logger:
  project: socialnav_downstream
  entity: daeun-song-george-mason-university
  mode: online
  experiment_name: socialnav_downstream_e${train_params.epochs}