dataset:
  index_file: "data/processed/samples/samples_val_index.json"
  only_human_visable: true
  resize: [192, 192]
  metric_waypoint_spacing: 1.0

eval_params:
  batch_size: 16
  num_workers: 4

model:
  d: 256
  input:
    T_obs: 6
    T_pred: 6
    N_human: 3
    N_joints: 17
  image_encoder:
    name: resnet18
    pretrained: true
    freeze_bn: true
    freeze_stem: false
    channels_last: true

directory:
  downstream_ckpt: checkpoint/downstream/socialnav_downstream_e30_20250821_best_s2.pth
  out_path: /home/songd/research/pose2nav/pose2nav/validation/val_results_20250823.pkl
