dataset:
  sample_file: "data/scand/val/samples.pkl"
  train: false
  only_human_visable: true
  only_nonlinear: true
  resize: [224, 224]  # decrease
  metric_waypoint_spacing: 1.0

dataloader:
  num_workers: 12  # increase #######
  batch_size: 32   # increase #######
  shuffle: True # whether to shuffle data or not
  pin_memory: True # use pageable memory or pinned memory (https://developer.nvidia.com/blog/how-optimize-data-transfers-cuda-cc/)
  drop_last: true
  persistent_workers: true
  prefetch_factor: 4

model:
  d: 384
  human_pool_temp: 1.0

  input:
    T_obs: 6
    T_pred: 12
    N_human: 3
    N_joints: 17

  image_encoder:
    name: dino
    pretrained: true
    frozen: true

  obs_transformer:
    layers: 3
    heads: 4      # increase #######
    ff_mult: 4
    dropout: 0
    norm: preln        # or "postln"

  projector:
    use: true
    d_out: 1024          
    hidden: 512       

  downstream:
    goal_encoder:
      dims: [64,256] # MLP dimensions
      l_act: False 
      dropout: 0.2
      bias: True
  
    head:
      dims: [256, 64]
      l_act: False 
      dropout: 0.2
      bias: True

loss_params:
  vicreg:
    sim_coef: 25.0
    std_coef: 25.0
    cov_coef: 3.0
    # eps: 1e-4

directory:
  downstream_ckpt: /home/songd/research/pose2nav/checkpoint/downstream/socialnav_downstream_d384_e50_exp24_20250913_best.pth
# downstream_ckpt: /home/songd/research/pose2nav/checkpoint/endToend/socialnav_downstream_d384_e50_exp22_20250911_best.pth
  out_path: /home/songd/research/pose2nav/pose2nav/validation/val_results_exp24.pkl
