dataset:
  index_file: "data/processed/samples/samples_val_index.json"
  only_human_visable: true
  only_nonlinear: true
  resize: [224, 224] #[192, 192]
  metric_waypoint_spacing: 1.0

eval_params:
  batch_size: 16
  num_workers: 4

model:
  d: 1024  # Must match the d_out in pretext
  d_goal: 64
  d_hidden: 1024

  input:
    T_obs: 6
    T_pred: 6
    N_human: 3
    N_joints: 17

  image_encoder:
    name: dino
    pretrained: true

  obs_transformer:
    layers: 3
    heads: 4
    ff_mult: 4
    dropout: 0.1
    norm: preln        # or "postln"

  projector:
    use: true
    d_out: 1024          # output dim of z_obs / z_traj
    hidden: 1024       

  # downstream
  future_traj_encoder:
    hidden: 1024
    num_layers: 1

directory:
  downstream_ckpt: checkpoint/downstream/socialnav_downstream_e50_20250901_best.pth
  out_path: /home/songd/research/pose2nav/pose2nav/validation/val_results_20250901.pkl
